### ISSUE TITLE
no ePub chapters when using pandoc-citeproc

### ISSUE THREAD

**Issue by iGormilhit** [jgm/pandoc-citeproc#104]
I'm making some test to learn how to use pandoc for my purposes. I'm trying to produce an ePub, with some citations in it. I have some files : `title.txt`, `test.md` which is the main part, `test-end.md` which holds the title of the references section, and of course a biblatex and a csl file.

When I don't use the `--filter pandoc-citeproc`, I get the chapter, with the `<h1>` on a new page, but of course no citation and no reference. The other way, when I use `--filter pandoc-citeproc`, I get the citations and references, but there's no chapter (the `<h1>` doesn't start on a new page).

My two pandoc commands : 

```
pandoc -S --filter pandoc-citeproc -o test-bib.epub title.txt test.md test-end.md
pandoc -S -o test-chapter.epub title.txt test.md test-end.md
```
Using `--epub-chapter=1` doesn't help.

Am I doing something wrong ?

**Comment by jgm** [comment]
I think I can see what's happening here.

pandoc-citeproc wraps the final references section in a special Div:

```
% echo "# Chapter\n\n# References" | pandoc -t json -s | pandoc-citeproc
% | pandoc -f json -t native 
[Header 1 ("chapter",[],[]) [Str "Chapter"]
,Div ("",["references"],[]) [Header 1 ("references",["unnumbered"],[])
[Str "References"]]]
```

But when the epub writer splits chapters, it doesn't descend into Divs,
so this doesn't get to be a separate chapter.

Related to jgm/pandoc#1776.  Probably the best solution is to modify the
epub chapter splitting algorithm so that it puts any Div that contains
top-level headers into their own chapter.

As a workaround you could apply a filter after pandoc-citeproc that
removes the Div with class "references" (i.e. replaces it with its
contents).

**Comment by iGormilhit** [comment]
Okay. Thank you for your answer. I think I'll need time and some work to be able to use the workaround you suggested. :)

**Comment by jgm** [comment]
I believe this is fixed by changes in the last release.  Let me know if not.
