### ISSUE TITLE
Use `default.csl` instead of `chicago-author-date.csl`

### ISSUE THREAD

**Issue by cinaeco** [jgm/pandoc-citeproc#161]
While setting up to use pandoc, I ran into small issues getting a default CSL (https://github.com/jgm/pandoc/issues/2372).

Users can currently set a default CSL by creating `~/.csl/chicago-author-date.csl`. This works, but renaming/symlinking `some-other-style.csl` to `chicago-author-date.csl` feels strange.

Should we change pandoc-citeproc to instead look for `~/.csl/default.csl`?

Also wondering: is there a reason pandoc-citeproc settings are split out into `~/.csl` instead of being kept with other pandoc settings in `~/.pandoc`?  Seems they might sit well in a subfolder e.g. `~/.pandoc/csl`.

**Comment by davepwsmith** [comment]
I think ~/.csl is a good default location for .csl files, which can be used by plenty of other programs besides pandoc. Fully in favour of there being a default .csl file for pandoc named defauld.csl, but I think it should probably live in ~/.pandoc so that it doesn't get muddled in with a pool of .csl files which might be used by (for example) Zotero. 

For me, the ideal situation would be:

```
~/.pandoc/default.csl #pandoc's default csl file, which you can symlink or whatever.
~/.csl/ #location for all other csl files
```

I would actually like to see this approach taken up by other CSL-using-programmes, but that seems less likely!

**Comment by adikari** [comment]
I am in favor with having the `~/.pandoc/default.csl`. This would simplify my current workflow a lot. Also I wouldn't prefer to have `~/.csl` but @davepwsmith makes the point with other program reading the csl.

**Comment by jgm** [comment]
I have adopted @davepwsmith 's suggestion.
