### ISSUE TITLE
Problem with link-citations using docx writer

### ISSUE THREAD

**Issue by mickley** [jgm/pandoc-citeproc#205]
When link-citations is true and output is to docx, the citations have links, but the links do not go anywhere.  

This is in contrast to section links such as [Citation Section](#section), which do work.  There are also no problems in latex/html5 output.

**Comment by lingdian618** [comment]
I got a similar problem. The links in my docx file always go to top of document.
Have you solved this?
Any suggestions?

**Comment by jgm** [comment]
Please give the versions of pandoc and pandoc-citeproc you're using.

**Comment by lingdian618** [comment]
pandoc 1.16
pandoc-citeproc 0.9
windows 8.1

**Comment by mickley** [comment]
pandoc 1.16.0.1
pandoc-citeproc 0.9
OSX 10.11.1 (Also Windows 7)

The same problem was present in pandoc 1.15 and pandoc-citeproc 0.8 though.

**Comment by lingdian618** [comment]
I noticed that hyperlink in word has not been generated correctly, so it goes to top of document when you click with ctrl hold.

For example, "#ref-selemon_reduced_1999" is one hyperlink in my case, but there's no bookmark named "#ref-selemon_reduced_1999". When I tried to new a bookmark named "#ref-selemon_reduced_1999" manually, I found that bookmark name in word can not contains the character "-". I guess this is the problem.

I hope this would be useful for somebody to fix this.

**Comment by alexstoick** [comment]
@jgm If you point me in the right direction I can try writing a patch for this 👍

**Comment by jgm** [comment]
This fix will have to be in pandoc itself, not here.  The changes would be to src/Text/Pandoc/Writers/Docx.hs.

We'd need to add a function to transform identifiers to a format suitable for docx (changing `-` to `_`; perhaps other changes are also needed?)

Then you'd need to apply this function when a bookmark is created.  Currently that's just in the clause for Header at l. 817ff, but maybe some of this should be factored out into a separate function, since later we might want to create bookmarks for Div and Span elements with an identifier.  (Indeed, it's probably this that's the problem; the links to citations link to Div elements with ids, and the docx writer doesn't currently create bookmarks for these.)

You'd also need to apply the identifier-munging function to the handler for internal links at l. 1155ff.

**Comment by jgm** [comment]
I've just about got this done.  It wasn't the hyphens, it was the other issue I indentified above.

**Comment by jgm** [comment]
OK, I think this is fixed, but you should compile pandoc from source and test.

**Comment by alexstoick** [comment]
@jgm Can confirm that this works now!

**Comment by timtroendle** [comment]
Any release plans for this fix? I am running into the same issue and would prefer to not build from source if possible.

**Comment by jgm** [comment]
Not in the near future.  But you can grab a binary from
https://github.com/pandoc-extras/pandoc-nightly
