### ISSUE TITLE
Referencing Author and Page not working with Numeric Style

### ISSUE THREAD

**Issue by W4RH4WK** [jgm/pandoc-citeproc#209]
I am not sure whether this is a problem with pandoc-citeproc or just the `.csl` files. References of the author's name or book page are omitted when using numeric style references. They work fine with natbib or when a author-year style is used.

Code:
```
## Citation

Blah Blah [see @wiki:denuvo]

Blah Blah [@rfc5246]

Blah Blah [@schneier2000, pp.33-35]

Something something as defined by @vernam1919.
```

pandoc-citeproc left, natbib right:
- - -
![image](https://cloud.githubusercontent.com/assets/328798/12378274/23485f7a-bd39-11e5-90f2-477efded130e.png)

pandoc-citeproc with author-year style:
- - -
![image](https://cloud.githubusercontent.com/assets/328798/12378286/4ddae276-bd39-11e5-96ec-83b27d830dc5.png)

**Comment by jgm** [comment]
CSL itself doesn't actually have the category of "in-text"
citations, that's a pandoc-citeproc addition.

I can't now recall why we do it this way, not including
the author's name.  Was there a reason?

Some numerical styles want this format:

    Reference 1 says...

Others want:

    [1] says...

and maybe some want, as you do:

    Author [1] says...

Since CSL styles don't have a category for "in-text"
citations, we can't control this in the style, so pandoc
has tried to find a reasonable default behavior.  Currently,
in the most recent version, it's just to print the number
(without brackets).  At least this allows authors to supply
the other material that's needed for their application.

+++ Alex Hirsch [Jan 17 16 07:45 ]:

**Comment by W4RH4WK** [comment]
I see. Personally I'd like to have same behavior than natbib. But, as you have already elaborated, this won't fit everybody. Guess this issue can be closed.

**Comment by jooolia** [comment]
Hello, I just came across this issue too and thought that it was something that I was doing. I too expected the same behaviour as natbib. However, as it is the expected behaviour I see that the solution is to go back to my text and add in the author names manually. 
Thanks for your work on this project!
