### ISSUE TITLE
pandoc-citeproc --bib2json never (?) finishes converting a record with very large numbers of authors

### ISSUE THREAD

**Issue by mz2** [jgm/pandoc-citeproc#228]
I've noticed that bib2json struggles in a big way with references which have very large numbers of authors. 

Examples is attached of a single record which does not seem to finish being processed (example provided in both MODS and EndNote XML, run below with MODS).

```
pandoc-citeproc -fmods --bib2json example.mods
```

[Archive.zip](https://github.com/jgm/pandoc-citeproc/files/267012/Archive.zip)

**Comment by jgm** [comment]
pandoc-citeproc uses the hs-bibutils library to convert from mods.
This is a wrapper around the bibutils library.
https://sourceforge.net/p/bibutils/home/Bibutils/

This appears to be an issue with bibutils itself, as you
can verify by running the command-line tool xml2bib (which
comes with bibutils) on your example.mods.

You should close this and report the bug upstream at
bibutils.

+++ Matias Piipari [May 16 16 14:42 ]:

**Comment by mz2** [comment]
I noticed the same soon after reporting it. For others being hit by the same issue, I have worked around this with a kludge involving extracting out author lists from the MODS data, running the conversion to my output format without author data, then injecting the author data back (I told you it's a kludge! :-)). Will next see if I manage to fix the issue in bibutils itself.

**Comment by jgm** [comment]
If you do get it fixed in bibutils, could you report back
here?  We'll try to make sure we get a new version of
bibutils-hs that incorporates the fix.

+++ Matias Piipari [May 17 16 05:22 ]:

**Comment by nickbart1980** [comment]
Like #229, I don’t think this is a bibutils issue:

If I’m not mistaken, pandoc-citeproc itself parses MODS, bibtex, biblatex, CSL JSON, and CSL YAML. (IIRC, citeproc-hs used to parse MODS and CSL JSON only.) Only for other formats, bibutils is called first to convert the format to MODS.

Admittedly, 5100 authors as in the example is a bit much, but pandoc-citeproc should be able to either handle them or exit with an error message.

**Comment by mz2** [comment]
OK. The translation of original EndNote XML to MODS (that definitely is done by bibutils) is actually reasonably fast indeed. I'll reopen then?

> Admittedly, 5100 authors as in the example is a bit much

Unfortunately, going over 1K is not uncommon with papers from large biomedical consortia or CERN for instance. How meaningful that is is one question, but bibliographic records of this kind do appear in specific fields.

**Comment by nickbart1980** [comment]
More observations:

Processing of `example.mods` *does* finish if you wait long enough (on my 2011 MacBook Air: > 1 h).

Also, `example.mods` isn’t exactly well-formed: it contains an unbalanced `</modsCollection>`. If this is removed, the same conversion takes “only” 19 min.

Finally, some weird case conversion takes place, see #231.

**Comment by mz2** [comment]
Oh yes, my example was not the most helpful in that, that was my bad. I have worked around this issue in my own codebase by selectively cutting out the contributor info from the MODS XML, doing a conversion of it myself to Citeproc JSON, and then injecting that into the otherwise complete Citeproc JSON. I haven't timed it exactly but it's well below a second.

**Comment by jgm** [comment]
@nickbart, pandoc-citeproc does not parse MODS.  A function from bibutils is used to convert from the target format (e.g. MODS or RIS) to bibtex, and then pandoc-citeproc parses the bibtex to get the references.

Running `xml2bib example.mods` shows that (at least a large part of) the slowdown is in bibutils itself, not pandoc-citeproc's bibtex parsing.  We could confirm further by running the output of that command through `pandoc-citeproc` to see if there is additional slowdown in bibtex parsing.

Note that this also explains the case conversion issues in #231, since bibtex is being used as an intermediary.  We could eliminate all case conversion by doing an extra pass that adds an extra enclosing `{}` in the title field before parsing the bibtex, though that's a bit ugly.

In principle we could build a native MODS parser in pandoc-citeproc -- parsing XML is pretty easy.  I don't know how widely used MODS is.

**Comment by nickbart1980** [comment]
@jgm: So you’re saying that the citeproc-hs approach of having bibutils convert everything (except CSL JSON) to MODS first, and then parsing MODS has been replaced, wholesale, by one that has bibutils convert everything (except bibtex, biblatex, CSL JSON/YAML) to bibtex first, and then parsing bibtex? If so, apologies, I really wasn’t aware of that.

What I liked about the citeproc-hs approach was that it needed just one potentially lossy conversion step by bibutils (X to MODS), instead of the two (X to MODS to bibtex) apparently required now. Also, MODS is much more expressive than bibtex (not sure whether any of Copac, EndNote, ISI, MEDLINE, RIS are more expressive than bibtex; biblatex certainly is).

citeproc-hs had a native MODS parser which seemed to work reasonably well, and the code should still be available. The big problem back in the day that led to the creation of pandoc-citeproc was not really the MODS parser but the fact that biblatex2xml contained too many bugs and lacked features, and its maintainer became unresponsive.

**Comment by jgm** [comment]
+++ nickbart1980 [May 24 16 01:39 ]:
>   [1]@jgm: So you’re saying that the citeproc-hs approach of having
>   bibutils convert everything (except CSL JSON) to MODS first, and then
>   parsing MODS has been replaced, wholesale, by one that has bibutils
>   convert everything (except bibtex, biblatex, CSL JSON/YAML) to bibtex
>   first, and then parsing bibtex? If so, apologies, I really wasn’t aware
>   of that.

Correct.  This was done in f5659c4815f6927d9181cd7c2a5fbbf3e22cb2a1.
I don't fully recall the reason now, but given the timing it
probably had to do with the change from String titles to
[Inline] titles (titles that can contain pandoc formatting,
such as math).

>   citeproc-hs had a native MODS parser which seemed to work reasonably
>   well, and the code should still be available. The big problem back in
>   the day that led to the creation of pandoc-citeproc was not really the
>   MODS parser but the fact that biblatex2xml contained too many bugs and
>   lacked features, and its maintainer became unresponsive.

I can look into bringing this back.  I can't recall whether
removing it was motivated just by the desire to simplify and
reduce the code base or by more substantive reasons.

I'd be more inclined, though, to rewrite (or have someone
else rewrite) this parser using the xml parsing framework
we're using now (especially because the citeproc-hs parser
depends on a complex Pickle module and would introduce a
dependency on another xml parsing library).

**Comment by jkr** [comment]
> I'd be more inclined, though, to rewrite (or have someone else rewrite) this parser using the xml parsing framework we're using now (especially because the citeproc-hs parser depends on a complex Pickle module and would introduce a dependency on another xml parsing library).

@jgm I've been interested in getting my feet wet with the pandoc-citerproc code, and I was thinking of attempting---or at least messing around with---the rewrite you mention here. But I want to be sure I understand the goal: would it be, essentially, to rewrite Input.Mods using xml-conduit? 

Unless there are other pressing TODOs in the codebase that you'd point me to?

(Also: is the long-term goal to remove the bibutils dependency and get all the parsers/writers into pure haskell?)

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Aug 19 16 07:44 ]:
>     I'd be more inclined, though, to rewrite (or have someone else
>     rewrite) this parser using the xml parsing framework we're using now
>     (especially because the citeproc-hs parser depends on a complex
>     Pickle module and would introduce a dependency on another xml
>     parsing library).
>
>   [1]@jgm I've been interested in getting my feet wet with the
>   pandoc-citerproc code, and I was thinking of attempting---or at least
>   messing around with---the rewrite you mention here. But I want to be
>   sure I understand the goal: would it be, essentially, to rewrite
>   Input.Mods using xml-conduit?

Yes, that was the idea.

>   Unless there are other pressing TODOs in the codebase that you'd point
>   me to?
>
>   (Also: is the long-term goal to remove the bibutils dependency and get
>   all the parsers/writers into pure haskell?)

I had no such ambition, though if someone wanted to do this
for some particular format, it would of course be an
improvement.
