### ISSUE TITLE
Incorrect case of collection titles in bibliography when citing article out of collection 

### ISSUE THREAD

**Issue by riolties** [jgm/pandoc-citeproc#239]
When citing an article or chapter out of a collection, the case of the collection title in the bibliography is always wrong. The first letter of the first word is capitalized (as it should be) and every word afterwords is lowercase (which they shouldn't). Like this:

Kenis, Patrick, and Volker Schneider. 1991. Policy Network and Policy Analysis: Scrutinizing an New Analytical Toolbox. In _Policy networks_, ed. Renate Mayntz and Bernd Marin, 25–59. Campus Verlag. 

The title of the collection should be written Policy Networks, not Policy networks. When citing the collection as a whole, the case of the words is correct:

Mayntz, Renate, and Bernd Marin, ed. 1991. _Policy Networks_. Empirical Evidence and Theoretical Considerations. Frankfurt/Main: Campus Verlag.

The CSL style used here is: [Springer Humanities Author-Date](https://github.com/citation-style-language/styles/blob/master/springer-humanities-author-date.csl)

But I tried multiple CSL styles and it seems to be an issue with citeproc. When using the same CSL style with Papers for example, the case of the words is correct.

I attached the .md and the .bib file for repro.
[collection_test.zip](https://github.com/jgm/pandoc-citeproc/files/321245/collection_test.zip)

**Comment by nickbart1980** [comment]
Not a pandoc-citeproc bug. The style in question contains no instructions for title-casing `title` or `container-title` (see https://github.com/citation-style-language/styles/blob/master/springer-humanities-author-date.csl#L186, https://github.com/citation-style-language/styles/blob/master/springer-humanities-author-date.csl#L190, https://github.com/citation-style-language/styles/blob/master/springer-humanities-author-date.csl#L335).

Whenver you are seeing title case in the output, this is merely due to the fact that some fields in your bib file are (incorrectly) wrapped in two pairs of braces. Remove one or else pandoc-citeproc cannot do its job properly.

If title-casing in the output is a must, use a different style.

**Comment by riolties** [comment]
Thanks for the reply. I suspected a pandoc-citeproc bug, as the output from the Papers citation assistant is correct based on the same bib and csl file. I'm not very familiar with the CSL format, but I expected `collection-title` to be the relevant macro, where `text-case` is set to `title` (see https://github.com/citation-style-language/styles/blob/master/springer-humanities-author-date.csl#L365-367). Any hint which parameters to change so that the bibliography shows the title the way it is written in the bib file?

The bib file itself is correct, just one pair of braces. However, as a workaround I can add a pair of braces so that pandoc-citeproc doesn't change the title to lowercase.

**Comment by nickbart1980** [comment]
Add `text-case="title"` to L187, L190, L335.

**Comment by riolties** [comment]
Thanks!

**Comment by mfransham** [comment]
I had this problem too - thanks for the solution!  I don't know why the CSL files don't include this as standard, though.
