### ISSUE TITLE
Extra comma with \noindent command

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#243]
Using a note style with a reference that does not begin with an author (whether because there is no author or it is printed later, as with an edited work for MHRA), if I place the citation in a footnote, preceded by a `\noindent` command, pandoc 1.17.1/pandoc-citeproc 0.10 adds a comma before the citation.

``` md
pandoc -F pandoc-citeproc --csl=chicago-fullnote-bibliography.csl << EOT

---
references:
- id: 'test'
  type: book
  title: Book title
...

Test text.[^1]

[^1]: \noindent @test [p. 196].

EOT
```

Result:

``` html
<p>Test text.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
<div id="refs" class="references">
<div id="ref-test">
<p><em>Book Title</em>, n.d.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Test footnote.</p>
<p>, <span class="citation"><em>Book Title</em>, n.d., 196</span>.<a href="#fnref1">↩</a></p></li>
</ol>
</div>
```

(Before someone points out that this is unnecessary: I needed to do this in a multi-paragraph footnote, following a block quotation.)

**Comment by jgm** [comment]
I can explain why this happens.  I don't know if I'd
consider this a bug; you're running up against the kind
of problem that typically arises when you use a note style
inside a note.

Pandoc has a `deNote` function that removes notes from
inside notes.  (The @test citation originally gets
turned into a note, since it's a note style.)  This function
inserts a comma between "non-spacelike" content and the
contents of the note.  Here it's treating `\noindent` as
non-spacelike (because it's not a Space or SoftBreak).

+++ Andrew Dunning [Jun 30 16 23:46 ]:
