### ISSUE TITLE
Print bibliographic entry inline

### ISSUE THREAD

**Issue by jackweinbender** [jgm/pandoc-citeproc#248]
I couldn't find any mention of this in the docs, so apologies if this has already been discussed. I'd like to be able to explicitly print out a specific bibliography item, rather than it's "citation." My use case: I'm compiling biographical information about a bunch of authors in a single document. After each author, I'd like to be able to list a few of their notable works as full bibliography items.

I'm imagining being able to just use `[@citekey]` notation, but with some kind of modifier like the author-suppressed citation form.

    ## Notable Works
    [+cross1973]
    [+cross1998]

would yield:

    Cross, Frank Moore Jr. Canaanite Myth and Hebrew Epic: Essays in the History 
          of the Religion of Israel. Cambridge, Mass.: Harvard University 
          Press, 1973.

    ———. From Epic to Canon: History and Literature in Ancient Israel. Baltimore:
          Johns Hopkins University Press, 1998.

I've seen folks request things like "multiple bibliographies" and I think this could also be a workaround for that use case—even if it requires manually referencing each work, which isn't ideal.

**Comment by jgm** [comment]
I think it's possible to use a CSL style that will print
the complete reference instead of a citation, and would omit
a bibliography; this would give you what you want.  I seem
to recall discussion on this issue, so you might search the
pandoc-discuss archives (on google groups) for something
like "annotated bibliography".

+++ Jack Weinbender [Jul 11 16 08:21 ]:
