### ISSUE TITLE
Problem: citation keys which contain a '+' char are not processed correctly

### ISSUE THREAD

**Issue by sappo** [jgm/pandoc-citeproc#259]
Hi,

I have a bibtex citation which includes a '+' char in its citation key which is not processed correctly using latest citeproc from cabal.

The bibtex entry looks like this:
```
@article{HFH+:WEKA:09,
  title = {The {{WEKA}} Data Mining Software: An Update},
  ...
}
```

And the citation in markdown is the following: `[@HFH+:WEKA:09]`. When running pandoc the following Warning/Error is printed: `pandoc-citeproc: reference HFH not found`.

**Comment by jgm** [comment]
Pandoc MANUAL.txt says: Citation keys may contain "internal
punctuation."  What that means in general is that the punctuation
should not be adjacent to other punctuation or spaces.

Why?  Because we need to handle cases like

    blah blah (see @foo):

Here we don't want to parse the key as `@foo):`.

There may be better heuristics though.

+++ Kevin Sapper [Oct 11 16 05:14 ]:

**Comment by jgm** [comment]
Just to be clear, I believe this is a pandoc issue (and
not necessarily a bug), not a pandoc-citeproc issues.
As you can see by doing `pandoc-citeproc -y my.bib`,
pandoc-citeproc itself has no trouble with this citation
key.  But pandoc does not want to parse `@HFH+:WEKA:09` as
a single citation key.

**Comment by sappo** [comment]
@jgm thanks for clarifying. I do see the issue now. I'll adjust my citation keys accordingly.
