### ISSUE TITLE
pandoc-citeproc: when expecting a product (:*:), encountered Object instead

### ISSUE THREAD

**Issue by kdheepak** [jgm/pandoc-citeproc#265]
Hi @jgm,

I get the following error when trying to run pandoc-citeproc. I started getting this error after updating to Pandoc 1.18. It works fine with Pandoc 1.17.2.

```
pandoc --filter pandoc-citeproc --bibliography=./bib.bib -o doc.tex doc.md
pandoc-citeproc: when expecting a product (:*:), encountered Object instead
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

doc.md
```
[@citation]
```

bib.bib
```
@article{citation,
  title = {Title},
  journaltitle = {Journaltitle},
  shortjournal = {shortjournaltitle},
  author = {Authors},
  date = {2016}
}
```

Thoughts on what might going on?

**Comment by jgm** [comment]
The JSON serialization format changed in pandoc 1.18
(pandoc-types 1.17.x).

This means that you'll need to use a version of
pandoc-citeproc that is compiled against the same version
of pandoc-types as your version of pandoc.

If you use our binary packages, this is taken care of,
since they provide both pandoc and pandoc-citeproc. Just
be sure you get rid of any extra old versions of
pandoc-citeproc.

If you compile pandoc yourself, just be sure to compile
the latest version of pandoc-citeproc too.

+++ Dheepak Krishnamurthy [Nov 05 16 13:26 ]:

**Comment by kdheepak** [comment]
Thanks for the quick reply! I see. I did reinstall pandoc-citeproc using brew, but it did not link it. Using the right version of `pandoc-citeproc` worked.

**Comment by wigging** [comment]
@kdheepak I'm getting the same error. Can you give more details on how you solved this problem?

**Comment by kdheepak** [comment]
I just updated to the latest version and it solved it for me. If you are
having the same issue please post the version of pandoc and pandoc-citeproc
that you are using.

**Comment by wigging** [comment]
I got it working. Apparently I needed to fix the symlink that Homebrew was using for the pandoc-citeproc package.
