### ISSUE TITLE
url as citekey/referencekey

### ISSUE THREAD

**Issue by geniusupgrader** [jgm/pandoc-citeproc#308]
I want to use this citekey:
`[@https://ww3.cad.de/cgi-bin/ubb/forumdisplay.cgi?action=topics&number=527]`

from this bib file:
~~~
@misc{https://ww3.cad.de/cgi-bin/ubb/forumdisplay.cgi?action=topics&number=527,
  timestamp = {2017-11-15T12:28:11Z},
  title = {Foren Auf {{CAD}}.de, {{OpenFOAM}}},
  urldate = {2017-11-15},
  howpublished = {https://ww3.cad.de/cgi-bin/ubb/forumdisplay.cgi?action=topics\&number=527},
  file = {Foren auf CAD.de, OpenFOAM:/home/robin/Zotero/storage/ZZ7XAH64/forumdisplay.html:text/html}
}
~~~

but I get this failure message:
`pandoc-citeproc: reference https://ww3.cad.de/cgi-bin/ubb/forumdisplay.cgi?action not found`
Looks like the equal sign (`=`) is cutting off the remainder of the url.

But I don't know if this is a pandoc-citeproc issue, a bibtex issue, an encoding problem or something else. Maybe someone can try it?

Additional Info:
pandoc version: 1.19.2.1
panodoc-crossref version: 2.6.0
Happens from markdown to html with --standalone, default template, everything default.

**Comment by jgm** [comment]
It's a pandoc issue.  And it's not a bug, it's documented
behavior. Pandoc doesn't accept arbitrary citation keys,
mostly because we have to consider the case where a
citation is followed by punctuation, e.g.

    [@doe1999, p. 99]

    (as seen in @doe1999)

MANUAL says:

Citations go inside square brackets and are separated by
semicolons.  Each citation must have a key, composed of '@'
+ the citation identifier from the database, and may
optionally have a prefix, a locator, and a suffix.  The
citation key must begin with a letter, digit, or `_`, and
may contain alphanumerics, `_`, and internal punctuation
characters (`:.#$%&-+?<>~/`).

An "internal" punctuation character is one followed by
an alphanumeric.

We could try make this fancier, e.g. by treating `=` as
a non-punctuation character.  Perhaps a better approach
would be to use the existing uri parser and allow any
URI as a citation key.


+++ geniusupgrader [Nov 15 17 12:40 ]:

**Comment by geniusupgrader** [comment]
Thank you for the explanation @jgm , I've overlooked the documentation for that.
The only reason for me to use links as citekeys was because of zotero and its handling of webpages as citations. Normally I click on my zotero chrome extension, the site will be added to zotero and automatically exported as a bib. And because of this automatically process the bib entry for webpages don't get any author nor date, only title and url. So I had thought it would be a great Idea to use the url as the citekey. Another benefit is that I can see the link in my markdown and don't need to look into the bib-file.
I would say, when it's possible and there are no problems, why not using an (additional) uri parser for the keys?

**Comment by jgm** [comment]
I have a proof of concept in the `uri-cite-key` branch of pandoc.

**Comment by jgm** [comment]
Another approach would be to allow curly braces for arbitrary cite keys:
```
@{whatever you want here}
```

**Comment by phiresky** [comment]
Inside curly braces would be a good solution, I don't think adding more possible ambiguity is a great idea. Anyways, I would like this because it would make implicitly / automatic generating bibliographies directly from the URLs ([see here](https://i.imgur.com/tCavDip.gif)) possible.

**Comment by dhimmel** [comment]
+1 to a syntax that allows "arbitrary cite keys". Personally, I'm okay with not having spaces in citekeys, but perhaps this would be valuable for others.

A more flexible character set for citekeys would help with citation by persistent identifiers, where users cite works directly by a persistent identifier. Currently Manubot supports [various types of identifiers](https://github.com/manubot/rootstock/blob/b7e6f581fa6fb730bfe5e778e4fa455c8c1d9d33/USAGE.md#citations) including DOIs, PubMed IDs, ISBNs, URLs, and Wikidata IDs. However, DOIs and URLs often include forbidden characters for citekeys, so Manubot parses these prior to pandoc rather than using a pandoc filter.

**Comment by jgm** [comment]
@dhimmel you might open an issue on the pandoc bug tracker, since this would require a change in pandoc rather than here.

**Comment by dhimmel** [comment]
> you might open an issue on the pandoc bug tracker, since this would require a change in pandoc

Got it. Opened https://github.com/jgm/pandoc/issues/6026
