### ISSUE TITLE
Support biblatex field ids for citekey aliases

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc-citeproc#356]
The [biblatex manual](http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf) defines field "ids" as comma separated list of citation key aliases for the main citation key. pandoc-citeproc seems to [just ignore this field](https://github.com/jgm/pandoc-citeproc/blob/e1038a51d4ce6e21930520e312a91e2a989dd281/src/Text/CSL/Input/Bibtex.hs#L292). Instead it should allow to use alias ids for citation:

~~~
@book{foo,
  author = {Alice},
  year = {2042},
  ids = {bar, doz}
}
~~~

Then reference book `foo` in Markdown:

~~~markdown
@bar
~~~

**Comment by jgm** [comment]
Only way to do this would be to create several
references that are identical except for the id.
We could do that, though.

**Comment by njbart** [comment]
> Only way to do this would be to create several references that are identical except for the id.

I’m afraid this won’t work without further modifications. As it is, pandoc-citeproc creates two reference section entries in such cases, and disambiguates these. I’m not sure whether there are other workable solutions: Checking whether biblio database entries are identical (except for the citekey) *would* of course work in principle, but I have no idea what that would mean performance-wise. Other solutions might be to allow a field called `other-ids` or similar. (Arguably, this wouldn’t even infract upon the CSL specs, since the commonly used `id` field isn’t defined there either …)

(The reason I’m interested: zotxt allows users to define additional citekeys for an entry by adding these to a tag or a note – but if more than one citekey per entry is used in a pandoc document, the entry is duplicated in the references section as well. An easy workaround is to avoid using different citekeys for the same entry, but a more foolproof approach, if possible at all, would of course be welcome.)

MWE:

~~~
pandoc -s -F pandoc-citeproc -t plain << EOT

Snow is white [@item1, 1]. Water is wet [@item2, 2].

# References {-}

---
references:
- id: item1
  type: book
  author:
  - family: Doe
    given: Jane
  issued:
    - year: 2018
  title: A title
- id: item2
  type: book
  author:
  - family: Doe
    given: Jane
  issued:
    - year: 2018
  title: A title
...
EOT
~~~

Actual output:

~~~
Snow is white (Doe 2018a, 1). Water is wet (Doe 2018b, 2).

REFERENCES

Doe, Jane. 2018a. _A Title_.

———. 2018b. _A Title_.
~~~


Expected:

~~~
Snow is white (Doe 2018, 1). Water is wet (Doe 2018, 2).

REFERENCES

Doe, Jane. 2018. _A Title_.
~~~

**Comment by jgm** [comment]
Yes, actually, I think we could introduce an `other-id`s field.
This would require:

- changes in References module to add the field
- changes in the Bibtex parser to populate the field
- change `getReference` in References to also check the other ids

Not sure if that would suffice by itself, but it would be a start.
