### ISSUE TITLE
test suite has undeclared dependency on "pandoc-citeproc"

### ISSUE THREAD

**Issue by peti** [jgm/pandoc-citeproc#369]
The test suite depends on the `pandoc-citeproc` binary compiled in the very same build, but it does not declare that dependency. The result are run-time errors, i.e. when building with NixOS. To remedy that issue, make sure the dependency is declared, i.e. by adding

      build-tools:        pandoc-citeproc

to the test-suite stanza in the Cabal file.

**Comment by jgm** [comment]
This would apply to pandoc itself, too, since the test
suite runs the executable.

But I'm a bit concerned that NixOS is using build-tools in
a way that isn't really supported by cabal (which has
a prespecificed list of build-tools; anything else is
simply ignored).  See

https://github.com/haskell/cabal/issues/5726

which even talks of removing 'build-tools' from future
versions of cabal.

Saying that this is a build-tool also seems
semantically wrong: it is not needed to build the
test suite, only to run it.

I'm not sure what the solution is here, but you
might want to contribute to the issue thread above,
so that the NixOS perspective is represented.

In addition: it seems that in recent cabal,
build-tools is deprecated in favor of build-tool-depends.
But the documentation explicitly says: "A list of
Haskell programs needed to build [not: run] this
component."

**Comment by peti** [comment]
> This would apply to pandoc itself, too, since the test suite runs the executable. 

Possibly, yes, I haven't tested that yet.

> But I'm a bit concerned that NixOS is using build-tools in a way that isn't really supported by cabal 

Actually, this has nothing to do with NixOS. This is a feature of Cabal. See https://github.com/simonmar/alex/blob/68e12240d64f6d454a8b0013e0cd4d3eb451252b/alex.cabal#L148 for some "documentation" by @hvr. The dependency ensures that (a) the executable is built before the test suite is and (b) `cabal-install` will make it available in $PATH when the test suite is run. I'm not sure whether this behavior is documented anywhere. It probably is. I know about this from a conversion with @hvr, but I can't find the appropriate URL any more.

> haskell/cabal#5726 which even talks of removing 'build-tools' from future versions of cabal.

Yes, future versions of Cabal will use `build-tool-depends`, which has a more accurate syntax and better defined semantics (but behaves the same way as far as this ticket is concerned).

> Saying that this is a build-tool also seems semantically wrong: it is not needed to build the test suite, only to run it.

Yes, I agree. Alas, that is how the master of `cabal-install` chose to implement it. I'm just the messenger.
