### ISSUE TITLE
Output work titles with <i> instead of <em>?

### ISSUE THREAD

**Issue by Porges** [jgm/pandoc-citeproc#370]
At the moment titles are output in Pandoc with `<em>` around them. Could this be changed to `<cite>` instead? It has the same visual effect of italicizing by default, but is more semantically correct (and doesn't make screenreaders sound strange 😁)

**Comment by jgm** [comment]
Pandoc-citeproc generates a list of Pandoc inlines.
Pandoc has no way of knowing which Emph sections in
this are titles, so this can't easily be done.

**Comment by Porges** [comment]
I think the real source is that the CSL file only has e.g. `font-style="italic"`, so there's no semantic information there? It might be better to just generate `<i>` instead of `<em>`.

**Comment by jgm** [comment]
Can you say something about why screenreaders sound strange with `<em>` instead of `<cite>`?

**Comment by cormacrelf** [comment]
The theory: https://logrocket.com/blog/youre-using-em-wrong/

In practice: https://www.brucelawson.co.uk/2018/screenreader-support-for-text-level-semantics/amp/

Screen readers apparently don’t make any different stress sound or announcements by default, partly because the tags are overused, e.g. by every italic in Pandoc and AFAIK every other Markdown implementation. It seems like `<i>` would be a better choice than either, even for normal markdown italics elsewhere. `<cite>` doesn’t really make sense in the middle of a context that already represents a cite. Probably would make sense for footnote numbers, but then you’d have to ship CSS with every file to reverse the default italics.
