### ISSUE TITLE
Get bibliographic data via websocket

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc-citeproc#372]
Reading bibliographic data from files does not scale if you have a large bibliography and only cite a manageable subset of its entries. pandoc-citeproc should also support lookup of bibliographic data from a database or web service. The best lookup method seems to be a web socket: it can be referenced with a `ws://` or `wss://`. pandoc-citeproc would send citation ids and receive bibliographic data in CSL JSON format. 

P.S: My intended use case is [WikiCite](http://wikicite.org/) with more than 20 million bibliographic items so far.

**Comment by phiresky** [comment]
Another use case that I don't think is possible right now: Automatically fetching and caching ref data from URLs - almost everything I cite can be described by a single URL (e.g. Arxiv), for which I extract the citation automatically using Zotero anyways.

So it would make sense to just write `[@<url>]` in the markdown document, then pandoc-citeproc would fetch the CSL JSON via a REST api (or websocket, i don't care) from an adapter that would ask zotero to check whether the URL is in the database and if not get the citation using the [zotero connectors](https://github.com/zotero/zotero-connectors) which work for  most websites.

**Comment by cormacrelf** [comment]
You should implement this as a Lua filter. Collect all the citekeys, fire a single request with cURL and dump to JSON or whatever. Even cache it. Only difficulty would be merging the result. Also, I’m rewriting citeproc in Rust, and I’m not going to implement this feature there, so get yourself a portable solution.

It’s also much easier than trying to maintain a flexible HTTP client interface via only Pandoc metadata. Think about how painful authentication would be, and remaining calm, slowly walk away from that idea.

(Incidentally, I can see no reason why you would want websockets in a program that exits after usually about a tenth of a second of work. Don’t do that, it’s not what websockets are for.)

**Comment by phiresky** [comment]
You mean a filter that runs before citeproc, writes the result to a bibliography file which citeproc then reads (in the same filter pipeline)? Not sure if that works, are the filter processes started in a strictly sequential order?

**Comment by jgm** [comment]
phiresky <notifications@github.com> writes:

> You mean a filter that runs before citeproc, writes the result to a bibliography file which citeproc then reads (in the same filter pipeline)? Not sure if that works, are the filter processes started in a strictly sequential order?

Yes.

**Comment by nichtich** [comment]
It works,  but if pandoc-citeproc is called via pandoc option `--bibliography`, the bibliography file must exist before being written to by the filter and read afterwards by pandoc-citeproc. An empty file should be enough to start with.

**Comment by nichtich** [comment]
Ok, I still like the idea of querying CSL data via HTTP but workaround exists with filters. If the filter also has to convert data to CSL it unlikely to be implemented in Lua nevertheless. My [pandoc-wikicite](https://www.npmjs.com/package/pandoc-wikicite) filter is based on [citation-js](https://www.npmjs.com/package/citation-js) - this Node package can also fetch data via DOI and it can be extended by plugins for other data sources such as arxiv.org. We may reopen the issue once we have more CSL web services in the future to avoid local installation of pandoc filters.

**Comment by jgm** [comment]
Jakob Voß <notifications@github.com> writes:

>  We may reopen the issue once we have more CSL web services in the future to avoid local installation of pandoc filters.

Sounds good.

**Comment by phiresky** [comment]
I managed to write a filter that directly and transparently creates citations on the basis of URLs, supporting pretty much all websites of papers etc (same as Zotero):

![image](https://user-images.githubusercontent.com/2303841/62411750-5db26500-b5f8-11e9-86aa-23d46fa88831.png)

It completely skips the need to manage any bibtex files or whatever, since the filter directly puts the citations in the meta json for pandoc-citeproc.

I'm mentioning this here mostly since it was pretty hard to find these things that make the [zotero extractors](https://github.com/zotero/translators) work outside of a browser plugin:

- https://github.com/zotero/translation-server
- https://www.mediawiki.org/wiki/Citoid
- https://en.wikipedia.org/api/rest_v1/#/Citation/getCitation

I'll put it in a repo later.

**Comment by phiresky** [comment]
> I'll put it in a repo later.

For completeness: I finally managed to finish that filter. I changed the above syntax (instead of using citekeys: in frontmatter I just (ab)use the markdown link reference syntax). References are still output to `references` key in frontmatter so citeproc directly reads those without intermediary files. The repo is here: https://github.com/phiresky/pandoc-url2cite

It also works for just converting all links in a document to citations (the README converts to https://phiresky.github.io/blog/2019/pandoc-url2cite/ )
