### ISSUE TITLE
Support for author-only citations

### ISSUE THREAD

**Issue by krivit** [jgm/pandoc-citeproc#377]
Apologies in advance if this is the wrong repository for this request.

Currently, `pandoc-citeproc` lets you suppress the author via a hyphen, as in, `[-@jon90]`. It would be helpful to be able to suppress the year instead, particularly when using a possessive form, as in 

> *Jones (1990)* proposes accomplish this by reversing the polarity on the dilithium crystal. We disagree with *Jones*'s approach, because..."

(automatically inserted elements italicised).

In `LaTeX` + `natbib`, this can be accomplished via the `\citeauthor{}` macro, but as far as I can tell, there is no way to do this using `pandoc-citeproc`.

One possible syntax for this might be for `-@jon90` to suppress the year the way `[-@jon90]` suppresses the author. This is because in a typical use case, the year would be typeset in parentheses, whereas the author's name would be typeset without.

**Comment by sjktje** [comment]
This is basically what keeps me from using markdown and pandoc instead of LaTeX.

**Comment by cormacrelf** [comment]
I’m trying to remake this feature in a slightly different way over at citeproc-rs:

- it should not use variable suppression, and instead use a conditional test so that styles can define what to show inline and what to move into a note/cite.
- it should by extension eclipse the parallel citations feature of CSL-M and allow you to type any legal cases after one another with parties’ names suppressed, not just those the engine has guessed are parallel by checking that the title variable is identical, even though you might want to refer to multiple appeals with parties names reversed, see the note [here](https://determined-mcnulty-63df76.netlify.com/csl-m#2.5-Case-History)
- this author-only thing is good
- syntax gets a bit trickier, but the mental model is “select which part of the cite you want”. I don’t think a context-dependent meaning of `-@doe` maps well to this. `-@doe` should mean “DROP the author/parties/inline-able part” whether inside or outside square brackets and another symbol should do the opposite. Maybe `+@doe` would reflect this opposite.

Unfortunately I think adding a citation mode would be an AST change. If so let’s of course take it slow, I would like to spend a bit more time thinking about what the requirements are here.

**Comment by samueldodson** [comment]
See also https://github.com/jgm/pandoc/issues/2335, which requests a pandoc equivalent of the `\citeauthor` biblatex command.

**Comment by cormacrelf** [comment]
See also https://github.com/zotero/zotero/issues/1580, in which a pretty good range of 'narrative cites' was worked out, along with experimental support from style authoring perspective. This is probably what any new syntax would target.

**Comment by krivit** [comment]
@jgm, I saw that the project was deprecated in favour of [citeproc](https://github.com/jgm/citeproc). For the benefit of those arriving here via a Google Search or similar, is there now a way to have an author-only citation in Pandoc Markdown? Thanks in advance!

**Comment by jgm** [comment]
Not at this point, sorry. citeproc itself does have the capacity for this. You can add an issue to the pandoc tracker if you like.
