### ISSUE TITLE
pandoc-citeproc ignores \parencite?

### ISSUE THREAD

**Issue by baem2** [jgm/pandoc-citeproc#385]
I just found out that pandoc-citeproc does not add parens when \parencite is used in LaTeX. I do not know if this is a pandoc or a citeproc issue, but I thought I'll start here.

MWE:

```% test.tex
\documentclass{article}
\usepackage{biblatex}
\bibliography{mybib}

\begin{document}
Eine Zeile: \parencite[2]{author00:title}

Noch eine Zeile: (\cite[3]{author00:title})

\printbibliography
\end{document}
```

```
% mybib.bib
@Book{author00:title,
  author =   {Author},
  title =    {Title},
  publisher =    {Publisher},
  year =     {2000}
}
```

Converted with:
```
pandoc -f latex -t odt --bibliography=mybib.bib -o test.odt test.tex
```

(Note that the standard CSL adds parens for *every* citation. But there are styles that do not do that, and in those cases it makes sense to differentiate between \cite and \parencite).

**Comment by jgm** [comment]
I'm not sure there's much we can do about this.
Pandoc parses `\parencite{hi}` to a normal citation.
In many styles, this will be rendered as a
parenthesized citation; in others, it won't be; but
this is csl dependent.

There's not going to be a perfect translation between
biblatex and csl, since they have different ways of
doing things.
