### ISSUE TITLE
pandoc-citeproc changes order of footnote/punctuation?

### ISSUE THREAD

**Issue by baem2** [jgm/pandoc-citeproc#418]
I am converting a LaTeX article to odt for a journal. The journal wants to have the footnote numbers _before_ the punctuation. I changed that manually in the tex document, but it seems in some cases pandoc-citeproc is changing the order of numbers/punctuation.

Here's an MWE.
This is the LaTeX file:
```
\documentclass[]{article}

\begin{document}

1 Some text.\footnote{Test}

2 More text\footnote{Test}.

3 And even more%
\footnote{%
	Test
	}.

\end{document}
```
This is what I am running:
`pandoc --filter pandoc-citeproc -f latex -t odt -o test.odt test.tex`

In case 1 and 2 all is as expected, but in case 3 pandoc-citeproc changes the order, i.e. the dot appears before the footnote number. When I leave out the pandoc-citeproc filter, it does not happen (but that's not an option as I need it for bibliography).

So why is that and is there a way to change/fix it?

**Comment by baem2** [comment]
Hah, I now found notes-after-punctuation -- which fixes the problem for me. It is still weird that the footnotes are handled differently.

**Comment by jgm** [comment]
You found the solution. Closing.
It behaves this way because putting the footnote number after punctuation is standard in many styles.

**Comment by baem2** [comment]
Yeah, right, I see. But still it should behave this way also in case 2, which for some reason does not happen?

**Comment by jgm** [comment]
Reopening, because we might want to address this apparent inconsistency.
The difference is that in 3 you have a space (technically a SoftBreak) before the note.  The code for moving notes is currently sensitive to this.  I can't recall why, but the primary point of the note-moving code is to work well with markdown input like
````
This is my sentence [@cite].
````
in which there will always be a space before the citation.  It may be that somebody explicitly requested that we not move notes in other cases (like your #2), but I'd have to check the changelogs to see about that.

In any case, there's arguably a pandoc bug here, since in LaTeX there's really no space between `more` and the note in your case 3.  We probably shouldn't be parsing this as including a SoftBreak.
