### ISSUE TITLE
CSL style as JSON

### ISSUE THREAD

**Issue by hubgit** [jgm/pandoc-citeproc#458]
Would it be possible for `pandoc-citeproc` to support reading a CSL style as either JSON or XML, in the same way that `citeproc-js` does?

**Comment by jgm** [comment]
Can you link to an example of a JSON version of a CSL style? I haven't seen that

**Comment by denismaier** [comment]
I wasn't aware that citeproc-js can consume a style in json format, nor that styles in that format even exist. As far as I know, citeproc-js accepts bibliographic data in CSL json, and that's also possible with pandoc-citeproc.

**Comment by nathanlesage** [comment]
… I think there might be a conflation, because the bibliographical data is saved in JSON, whereas the styles are stored in XML.

I just did a quick [search on the citeproc docs](https://citeproc-js.readthedocs.io/en/latest/search.html?q=JSON&check_keywords=yes&area=default), and couldn't find any reference to _styles_ being in JSON format

Possibly, what OP is referring to is [the XMLJSON object within citeproc's codebase](https://github.com/Juris-M/citeproc-js/blob/7310d8400166221dd3e6d24767938aff283f7f32/citeproc_commonjs.js#L1490). I know there are some lesser known functions within that behemoth of a file, and it could be possible to just stuff it a JSON file generated from the original XML, bypassing the XML parsing. But the regular way, even for citeproc, is to just read the files in their XML format, and use JSON simply as the internal AST of these files.

**Comment by denismaier** [comment]
Ha, I've just remembered there was a discussion about this last year on the csl discoure forum. It seems citeproc-js can indeed use *styles* in json because it uses a json representation of styles itself. (see [this post.](https://discourse.citationstyles.org/t/styles-locales-as-xml-vs-json/1556/2?u=denis_maier)) But this is just citeproc-js's internal representation, and I would not expect other citeprocs to have the same or even a similar internal representation of styles.

**Comment by hubgit** [comment]
`citeproc-js` is able to read CSL styles as either XML and JSON and will [choose an appropriate parser](https://github.com/Juris-M/citeproc-js/blob/0935238d1eee88edb9ea3b3e59a00a4bdf46c5f6/src/system.js#L3).

Calling the `parseXml` function from `citeproc-js` will convert an XML style to an object, which can then be saved as JSON and loaded back into `citeproc-js` later.

A couple of packages - [citeproc-plus](https://github.com/fiduswriter/citeproc-plus) and [@manuscripts/csl-styles](https://gitlab.com/mpapp-public/csl-styles) - use this technique to bundle CSL styles as JSON into web applications, and when that data gets passed through `pandoc-citeproc` later it would be useful if it didn't need to be converted back to XML.

However, it's easy enough to write a function that either converts the JSON back to XML or simply points to the original XML file, so I'll close this issue.

**Comment by hubgit** [comment]
> this is just citeproc-js's internal representation, and I would not expect other citeprocs to have the same or even a similar internal representation of styles

This is a good point, and on reflection there wasn't enough benefit to storing styles as JSON so I've gone back to storing them as XML, avoiding any potential compatibility problems.
