### ISSUE TITLE
weird comma in front of year using DIN1505

### ISSUE THREAD

**Issue by MAWSpitau** [jgm/pandoc-citeproc#469]
Hi there, 

- I am using the https://github.com/citation-style-language/styles/blob/master/din-1505-2.csl for my citations.
- I always get a wierd comma in front of my year and I have no idea how to get rid of it

the citation in the markdownfile (in an footnote):
` [^3f261b3e]: @Spitau2019`

the bibtex entry
```
@Book{Spitau2019,
author    = {Spitau, Marcel},
title     = {Papier Im Griff - Vom Informationsbesitzer Zum Informationsbenutzer Mit Classei},
publisher = {Independently Published},
isbn      = {978-1-092-11316-8},
address   = {Printed in the United States of America},
year      = {2019},
}
```
And this is how it looks like... 
https://i.imgur.com/RYI68U0.png

I do not understand WHY there is the comma and I want to get rid of it.

Any ideas?

```
pandoc 2.11.3
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
This project isn't really maintained any more -- we have moved over to integrated citeproc support in pandoc (much better I might add) starting in 2.11.  You should not be using the `pandoc-citeproc` filter; instead, use the `--citeproc` command line flag on pandoc.  If you *are* doing that, then put your issue on jgm/citeproc instead of here.

**Comment by MAWSpitau** [comment]
Argh. Damn. of course I am using --citeproc sorry...
