### ISSUE TITLE
Incorrect IEEE citation style from CSL?

### ISSUE THREAD

**Issue by paul-g** [jgm/pandoc-citeproc#55]
Hi. I am using pandoc and [ieee.csl](https://github.com/citation-style-language/styles/blob/master/ieee.csl) for an IEEE conference and the generated citations lack square brackets and the bibliography is incorrectly formatted.

Please find the original issue I reported to CSL [here](https://github.com/citation-style-language/styles/issues/989).

My pandoc version is:
```
pandoc 1.10.1
Compiled with citeproc-hs 0.3.6, texmath 0.6.0.6, highlighting-kate 0.5.1.
```

**Comment by npdoty** [comment]
I see the original issue (no brackets around the citation number when using ieee.csl) in pandoc 1.13.1. (It's difficult to install an older version of pandoc side-by-side in order to verify on the same machine that this is a regression, but it seems so.)

For this input file:

    A survey can be found in [@Doty2013].

This command:
`pandoc -t plain test.mdown --bibliography=library.bib --csl=ieee.csl`
returns:
  
    A survey can be found in 1.

when the expected output is:

    A survey can be found in [1].

For the time being, I'm using the workaround (edits to the CSL file) described by sssimon in [https://github.com/citation-style-language/styles/issues/607]().

**Comment by baig** [comment]
I see the same issue with pandoc 1.13.1 described by @npdoty

**Comment by musteresel** [comment]
pandoc 1.13.1 with IEEE style "IEEE (with URL)" from zotero here, same issue.

**Comment by jgm** [comment]
Interesting.  We've been testing with an older version of the style, `tests/ieee.csl`.  It works fine with that version, but I confirm, not with the new version.

From what I can see at a first glanec, here's the salient difference.  New version has:
``` xml
     <layout delimiter=", ">
       <group prefix="[" suffix="]" delimiter=", ">
         <text variable="citation-number"/>
```

Old version had:
``` xml
     <layout prefix="[" suffix="]" delimiter="], [">
       <text variable="citation-number"/>
```

**Comment by jgm** [comment]
So I conjecture that prefix and suffix aren't working on `group` elements.

**Comment by adam3smith** [comment]
just chiming in to confirm that the current CSL style is correct in terms of producing IEEE output: The old version would do [1-3], the current one [1]-[3], which, bizarre as it looks to me, is what IEEE wants, see top of p. 34 [here](http://www.ieee.org/documents/style_manual.pdf). 

We're using a ton of affixes on groups in CSL styles, so if that's a general issue I'd have expected more error reports.

**Comment by frastlin** [comment]
I am still getting this problem of @bla2019 showing up as 1 rather than [1] in Pandoc 2.7. The strange thing is that the exact same citation, when run with the [ACM.csl](https://github.com/citation-style-language/styles/blob/master/acm-sig-proceedings.csl) works perfectly. So it really looks as if this can be fixed in the CSL file.

A [post](https://groups.google.com/d/msg/pandoc-discuss/72YLu7x74lk/jbFfcR4LAgAJ) from a discussion on the Pandoc email list gave a lua filter that achieves this result as well:

	function Cite (cite)
	  for _, c in pairs(cite.citations) do
	c.mode = pandoc.NormalCitation
	  end
	  return cite
	end

Paste this code into a .lua text file and in the pandoc command, do --lua-filter=luaFile.lua before citeproc.
