### ISSUE TITLE
Cannot compile: "ghc: memory allocation failed"

### ISSUE THREAD

**Issue by wrengr** [jgm/pandoc-citeproc#78]
When trying to install pandoc-citeproc 0.4.0.1 using GHC 7.8.2, the file Text.CSL.Input.Bibtex fails with the error "ghc: memory allocation failed". Unclear which of the two is to blame...

**Comment by winterkoninkje** [comment]
Same thing happens with pandoc-citeproc 0.6 and GHC 7.8.3

**Comment by winterkoninkje** [comment]
I managed to get it to finish compiling by disabling optimization (and profiling— because that was necessary to get texmath and hence pandoc to install without memory problems). After some testing, it looks like -O1 also finishes successfully. The problem just shows up with -O2 (which I have cabal set to use for the default).

**Comment by jgm** [comment]
How much memory does your system have?

+++ wren gayle romano [Jan 20 15 12:58 ]:

**Comment by winterkoninkje** [comment]
4GB

**Comment by jgm** [comment]
Very strange - I routinely compile these on lower-memory systems,
and on OSX with 4 GB.
