### ISSUE TITLE
Close quotes omitted for various references.

### ISSUE THREAD

**Issue by dfaligertwood** [jgm/pandoc-citeproc#82]
In reference styles such as chicago-note-annotated.csl which have some titles appearing in quotes, the final close quote is omitted in certain situations.

For example, the following:

```
[@OCLC_i1099]
^[Note on text, with citation and page number [@OCLC_i1099, p. 5]]
^[Note on text, [@OCLC_i1099] with some more text and no comma]
```

return (correctly)

> OCLC, “WorldCat.”

But the following:

```
^[Comment regarding text, supported by citation [@OCLC_i1099]]
^[Another comment, without brackets around citation @OCLC_i1099]
^[Note with citation [@OCLC_i1099], and some more text]
^[Note with unbracketed citation @OCLC_i1099, and more text]
^[Note on text, with citation @OCLC_i1099 followed by more text]
```

return (incorrectly):

> OCLC, “WorldCat.

Exemplar CSL-JSON bibliography:

```
[
{
  "id": "OCLC_i1099",
  "type": "webpage",
  "title": "WorldCat",
  "URL": "https://www.worldcat.org/",
  "author": [
    {
      "literal": "OCLC"
    }
  ],
  "accessed": {
    "date-parts": [
      [
        "2014",
        9,
        19
      ]
    ]
  }
}
]
```

This doesn't seem to happen if I export the citations from Zotero. I don't have word/openoffice working with the plugin, so I can't check there.

**Comment by Jmuccigr** [comment]
I'm running into this too with the society-of-biblical-literature-fullnote-bibliography.csl and the second reference to an article, which users their "title-short" macro. For example, upon second mention 

    @Loewenstamm1967Biblica

yields

    Loewenstamm, “The Making and Destruction of the Golden Calf.

Note that there's no need at all for the period.

I too am using the ^[] style for footnotes in my md and the problem seems to go away if I switch to simple in-line []. ("Doctor, it hurts when I do this.")

(Interestingly in that second case, something like ["Citing @Loewenstamm1967Biblica again."] will yield "Citing Loewenstamm, “The Making and Destruction of the Golden Calf" again." where you'd like there to be a comma after the article title, since there's one before it.)
